### ISSUE TITLE
Get MANE Select from GeneSymbol ?

### ISSUE THREAD

**Issue by JulieBlasquiz** [jdieramon/refseqR#14]
Hi !
Thanks for this useful package !

Is there a way to get the MANE Select from GeneSymbol ?

Thanks in advance 
Julie

**Comment by jdieramon** [comment]
Hi @JulieBlasquiz, could you provide a specific example with the accession ID and the field you’d like to fetch?

**Comment by JulieBlasquiz** [comment]
Sure !

For example, given the GeneSymbol **BRCA1**, (GeneID 672), the query would return the following NM: **NM_007294.4**

Julie

**Comment by jdieramon** [comment]
Thanks Julie. 

Actually, that feature was available in previous versions, but we removed it. The problem with using gene symbols is that they are not unique across datasets.  Issues may arise when a function call yields multiple identifiers.

There are some ways you can retrieve the gene symbol/gene name. 

      refseq_geneSymbol("NM_007294", db = "nuccore") # returns gene name.  
      [1] "BRCA1"


      refseq_geneSymbol("NP_009225", db = "protein") # returns gene name
      [1] "BRCA1"

However, using the symbol as input maps to nowhere when attempting to return the gene/mRNA/protein accessions.
At some point, to operate interchangeably between records, you need an accession ID (gene, RNA, or protein).

The symbol sometimes produces the expected result with the `refseq_description` function. Anyway, the best solution is to always use the GeneID. Therefore, the vignette now emphasizes that the argument of the function needs to be a transcript or protein ID, as well as a GeneID, because a gene symbol does not guarantee stable performance. Also, the help text in the function documentation includes : *Returns the sequence description from a single transcript, protein, or GeneID accession.*

      refseq_description('NM_007294')
      [1] "BRCA1 DNA repair associated"

      refseq_description("NP_009225")
      [1] "BRCA1 DNA repair associated"

      refseq_description("BRCA1")
      [1] "abraxas 1, BRCA1 A complex subunit"

**Comment by JulieBlasquiz** [comment]
Thank you for taking the time to reply with all this information

Now I understand why it's not relevant to use the GeneSymbol as query input

Thank you very much
Julie
